# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 898b2597bbf18ef9674d4fbc5368ae3fef2b60c02bfa35eab67cfa6f78a9bebf68def478e598d807397e62c19eee00dd0efe8118e98c32ce61c419ffe6844f8a

test:
  secret_key_base: 63993240dd401f54d5f7559128224dcc84e7dc71662ae3d9e715d596279ae7c80aa3b17a92d1cc2a2a9c2c70ba4c49e47913b00803c31d8c64f5a05583664f81

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
